-- MySQL Script generated by MySQL Workbench
-- 23 شباط, 2022 10:04:49 م
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema falcon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema falcon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `falcon` DEFAULT CHARACTER SET utf8 ;
USE `falcon` ;

-- -----------------------------------------------------
-- Table `falcon`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `shortName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`notification` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `sendMeDailyMissedCheckpointReport` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notification_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_notification_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `falcon`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`email` (
  `id` VARCHAR(45) NOT NULL,
  `fromEmailAddressNewOrder` VARCHAR(45) NULL,
  `fromEmailAddressNewIssue` VARCHAR(45) NULL,
  `fromEmailAddressAppeals` VARCHAR(45) NULL,
  `SystemEmailNotification` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`logos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`logos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mainPageLogo` VARCHAR(45) NULL,
  `reportHeaderLogo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`street_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`street_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `streetType` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`clients_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`clients_companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(45) NULL,
  `webAddress` VARCHAR(45) NULL,
  `notes` TEXT(1000) NULL,
  `streetNumber` VARCHAR(45) NULL,
  `streetName` VARCHAR(45) NULL,
  `streetType` VARCHAR(45) NULL,
  `street_types_id` INT NOT NULL,
  `city` VARCHAR(45) NULL,
  `states_id` INT NOT NULL,
  `zip` VARCHAR(45) NULL,
  `buildingNumber` VARCHAR(45) NULL,
  `mainPhone` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clients_companies_street_types1_idx` (`street_types_id` ASC) VISIBLE,
  INDEX `fk_clients_companies_states1_idx` (`states_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_companies_street_types1`
    FOREIGN KEY (`street_types_id`)
    REFERENCES `falcon`.`street_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_companies_states1`
    FOREIGN KEY (`states_id`)
    REFERENCES `falcon`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`properties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `propertyName` VARCHAR(45) NULL,
  `propertyCode` VARCHAR(45) NULL,
  `webAddress` VARCHAR(45) NULL,
  `primaryAddress` VARCHAR(45) NULL,
  `billingAddress` VARCHAR(45) NULL,
  `propertyNotes/PostOrders` TEXT(1000) NULL,
  `inCustomGroups` TEXT(1000) NULL,
  `securityProgram` TINYINT NULL,
  `maintananceProgram` TINYINT NULL,
  `parkingProgram` TINYINT NULL,
  `clients_companies_id` INT NOT NULL,
  PRIMARY KEY (`id`, `clients_companies_id`),
  INDEX `fk_property_clients_companies1_idx` (`clients_companies_id` ASC) VISIBLE,
  CONSTRAINT `fk_property_clients_companies1`
    FOREIGN KEY (`clients_companies_id`)
    REFERENCES `falcon`.`clients_companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`property_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`property_photo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `property_id` INT NOT NULL,
  `path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_propertyPhoto_property1_idx` (`property_id` ASC) VISIBLE,
  CONSTRAINT `fk_propertyPhoto_property1`
    FOREIGN KEY (`property_id`)
    REFERENCES `falcon`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`addresses_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`addresses_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `addressName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`property_addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`property_addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `property_id` INT NOT NULL,
  `streetNumber` VARCHAR(45) NULL,
  `streetName` VARCHAR(45) NULL,
  `streetType` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `property_addressescol` VARCHAR(45) NULL,
  `states_id` INT NOT NULL,
  `zip` INT NULL,
  `county` VARCHAR(45) NULL,
  `buildingNumber` VARCHAR(45) NULL,
  `addressType` VARCHAR(45) NULL,
  `property_addressescol1` VARCHAR(45) NULL,
  `addresses_types_id` INT NOT NULL,
  `GPSLongitude` VARCHAR(45) NULL,
  `GPSLatitude` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_property_addresses_property1_idx` (`property_id` ASC) VISIBLE,
  INDEX `fk_property_addresses_states1_idx` (`states_id` ASC) VISIBLE,
  INDEX `fk_property_addresses_addresses_types1_idx` (`addresses_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_property_addresses_property1`
    FOREIGN KEY (`property_id`)
    REFERENCES `falcon`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_property_addresses_states1`
    FOREIGN KEY (`states_id`)
    REFERENCES `falcon`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_property_addresses_addresses_types1`
    FOREIGN KEY (`addresses_types_id`)
    REFERENCES `falcon`.`addresses_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`alert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`alert` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `property_id` INT NOT NULL,
  `minimumIssuesCreatedPerHour` INT NULL,
  `issues_container` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_alert_property1_idx` (`property_id` ASC) VISIBLE,
  CONSTRAINT `fk_alert_property1`
    FOREIGN KEY (`property_id`)
    REFERENCES `falcon`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`property_documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`property_documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `property_id` INT NOT NULL,
  `documentName` VARCHAR(45) NULL,
  `fileName` VARCHAR(45) NULL,
  `path` VARCHAR(45) NULL,
  `documentDescription` VARCHAR(45) NULL,
  `allowCustomersToView` VARCHAR(45) NULL,
  `displayOnNewAction` VARCHAR(45) NULL,
  `propertyDocumentscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_propertyDocuments_property1_idx` (`property_id` ASC) VISIBLE,
  CONSTRAINT `fk_propertyDocuments_property1`
    FOREIGN KEY (`property_id`)
    REFERENCES `falcon`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`property_checkpoints`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`property_checkpoints` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `property_id` INT NOT NULL,
  `checkPointName` VARCHAR(45) NULL,
  `checkPointLocation` VARCHAR(45) NULL,
  `QR/NFCCodeValue` VARCHAR(255) NULL,
  `property_addresses_id` INT NOT NULL,
  `chckpointUnit` VARCHAR(45) NULL,
  `checkpintIssueType` VARCHAR(45) NULL,
  `autoCreateIssueType` TINYINT NULL,
  `checkpointLastHint` VARCHAR(45) NULL,
  `reportNote` VARCHAR(45) NULL,
  `officerInstructions` VARCHAR(45) NULL,
  `isActive` TINYINT NULL,
  `allowKeepOpen` TINYINT NULL,
  `requirePhoto` TINYINT NULL,
  `propertyCheckpointscol` TINYINT NULL,
  `reportIfMissed` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_propertyCheckpoints_property1_idx` (`property_id` ASC) VISIBLE,
  INDEX `fk_propertyCheckpoints_property_addresses1_idx` (`property_addresses_id` ASC) VISIBLE,
  CONSTRAINT `fk_propertyCheckpoints_property1`
    FOREIGN KEY (`property_id`)
    REFERENCES `falcon`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_propertyCheckpoints_property_addresses1`
    FOREIGN KEY (`property_addresses_id`)
    REFERENCES `falcon`.`property_addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`tourDaysOfWeek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`tourDaysOfWeek` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sunday` TINYINT NULL,
  `monday` TINYINT NULL,
  `tuesday` TINYINT NULL,
  `wednesday` TINYINT NULL,
  `thursday` TINYINT NULL,
  `friday` TINYINT NULL,
  `saturday` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`property_tours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`property_tours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `property_id` INT NOT NULL,
  `tourName` VARCHAR(45) NULL,
  `tourDescription` TEXT(1000) NULL,
  `tourStartTime` VARCHAR(45) NULL,
  `tourEndTime` VARCHAR(45) NULL,
  `allowManualSubmission` TINYINT NULL,
  `isActiveTour` TINYINT NULL,
  `tourDaysOfWeek_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_property_tours_property1_idx` (`property_id` ASC) VISIBLE,
  INDEX `fk_property_tours_tourDaysOfWeek1_idx` (`tourDaysOfWeek_id` ASC) VISIBLE,
  CONSTRAINT `fk_property_tours_property1`
    FOREIGN KEY (`property_id`)
    REFERENCES `falcon`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_property_tours_tourDaysOfWeek1`
    FOREIGN KEY (`tourDaysOfWeek_id`)
    REFERENCES `falcon`.`tourDaysOfWeek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`property_tours_has_property_checkpoints`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`property_tours_has_property_checkpoints` (
  `property_tours_id` INT NOT NULL,
  `property_checkpoints_id` INT NOT NULL,
  `order` INT NULL,
  PRIMARY KEY (`property_tours_id`, `property_checkpoints_id`),
  INDEX `fk_property_tours_has_property_checkpoints_property_checkpo_idx` (`property_checkpoints_id` ASC) VISIBLE,
  INDEX `fk_property_tours_has_property_checkpoints_property_tours1_idx` (`property_tours_id` ASC) VISIBLE,
  CONSTRAINT `fk_property_tours_has_property_checkpoints_property_tours1`
    FOREIGN KEY (`property_tours_id`)
    REFERENCES `falcon`.`property_tours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_property_tours_has_property_checkpoints_property_checkpoin1`
    FOREIGN KEY (`property_checkpoints_id`)
    REFERENCES `falcon`.`property_checkpoints` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`property_geofance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`property_geofance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `property_id` INT NOT NULL,
  `geofanceName` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `geofanceRadius` VARCHAR(45) NULL,
  `property_geofancecol` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_property_geofance_property1_idx` (`property_id` ASC) VISIBLE,
  CONSTRAINT `fk_property_geofance_property1`
    FOREIGN KEY (`property_id`)
    REFERENCES `falcon`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`issue_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`issue_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `issueTypeName` VARCHAR(45) NULL,
  `issueDescription` TEXT(1000) NULL,
  `issueFee` DOUBLE NULL,
  `issueLevel` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`issue_types_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`issue_types_options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `issue_types_id` INT NOT NULL,
  `isActiveIssue` TINYINT NULL,
  `displayForDispach` TINYINT NULL,
  `displayOnHandheld` TINYINT NULL,
  `displayForWebUsers` TINYINT NULL,
  `autoCloseIssue` TINYINT NULL,
  `restrictToCheckpointOnly` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_issue_types_options_issue_types1_idx` (`issue_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_issue_types_options_issue_types1`
    FOREIGN KEY (`issue_types_id`)
    REFERENCES `falcon`.`issue_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`issues_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`issues_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `issueTypeName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`issue_types_has_issues_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`issue_types_has_issues_types` (
  `issue_types_id` INT NOT NULL,
  `issues_types_id` INT NOT NULL,
  PRIMARY KEY (`issue_types_id`, `issues_types_id`),
  INDEX `fk_issue_types_has_issues_types_issues_types1_idx` (`issues_types_id` ASC) VISIBLE,
  INDEX `fk_issue_types_has_issues_types_issue_types1_idx` (`issue_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_issue_types_has_issues_types_issue_types1`
    FOREIGN KEY (`issue_types_id`)
    REFERENCES `falcon`.`issue_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issue_types_has_issues_types_issues_types1`
    FOREIGN KEY (`issues_types_id`)
    REFERENCES `falcon`.`issues_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`property_has_issue_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`property_has_issue_types` (
  `property_id` INT NOT NULL AUTO_INCREMENT,
  `issue_types_id` INT NOT NULL,
  PRIMARY KEY (`property_id`, `issue_types_id`),
  INDEX `fk_property_has_issue_types_issue_types1_idx` (`issue_types_id` ASC) VISIBLE,
  INDEX `fk_property_has_issue_types_property1_idx` (`property_id` ASC) VISIBLE,
  CONSTRAINT `fk_property_has_issue_types_property1`
    FOREIGN KEY (`property_id`)
    REFERENCES `falcon`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_property_has_issue_types_issue_types1`
    FOREIGN KEY (`issue_types_id`)
    REFERENCES `falcon`.`issue_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `locationName` VARCHAR(45) NULL,
  `locationDescription` TEXT(1000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`property_has_locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`property_has_locations` (
  `property_id` INT NOT NULL AUTO_INCREMENT,
  `locations_id` INT NOT NULL,
  PRIMARY KEY (`property_id`, `locations_id`),
  INDEX `fk_property_has_locations_locations1_idx` (`locations_id` ASC) VISIBLE,
  INDEX `fk_property_has_locations_property1_idx` (`property_id` ASC) VISIBLE,
  CONSTRAINT `fk_property_has_locations_property1`
    FOREIGN KEY (`property_id`)
    REFERENCES `falcon`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_property_has_locations_locations1`
    FOREIGN KEY (`locations_id`)
    REFERENCES `falcon`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`parking_setup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`parking_setup` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `property_id` INT NOT NULL,
  `maximumPermitsPerUnit` INT NULL,
  `permitSellCost` INT NULL,
  `cash/checkPremitCode` VARCHAR(45) NULL,
  `freePremitCode` VARCHAR(45) NULL,
  `maxLengthInDaysTempPermit` VARCHAR(45) NULL,
  `maxTempPermitsPerUnitPerMonth` INT NULL,
  `parking_setupcol` INT NULL,
  `sellParkingPermits` TINYINT NULL,
  `userVirtualPermit` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parking_setup_property1_idx` (`property_id` ASC) VISIBLE,
  CONSTRAINT `fk_parking_setup_property1`
    FOREIGN KEY (`property_id`)
    REFERENCES `falcon`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`parking_zones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`parking_zones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parking_setup_id` INT NOT NULL,
  `parkingZoneName` VARCHAR(45) NULL,
  `parkingZoneDescription` TEXT(1000) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parking_zones_parking_setup1_idx` (`parking_setup_id` ASC) VISIBLE,
  CONSTRAINT `fk_parking_zones_parking_setup1`
    FOREIGN KEY (`parking_setup_id`)
    REFERENCES `falcon`.`parking_setup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`phone_numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`phone_numbers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `property_id` INT NOT NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `phoneNumberType` VARCHAR(45) NULL,
  `displayInHandheld` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_phone_numbers_property1_idx` (`property_id` ASC) VISIBLE,
  CONSTRAINT `fk_phone_numbers_property1`
    FOREIGN KEY (`property_id`)
    REFERENCES `falcon`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`taskDaysOfWeek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`taskDaysOfWeek` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sunday` TINYINT NULL,
  `monday` TINYINT NULL,
  `tuesday` TINYINT NULL,
  `wednesday` TINYINT NULL,
  `thursday` TINYINT NULL,
  `friday` TINYINT NULL,
  `saturday` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`unites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`unites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `property_addresses_id` INT NOT NULL,
  `unitNumberPrefix` VARCHAR(45) NULL,
  `startingUnitNumber` INT NULL,
  `unitNumberIncrement` INT NULL,
  `endingUnitNumber` INT NULL,
  `unitNumberSuffix` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_unites_property_addresses1_idx` (`property_addresses_id` ASC) VISIBLE,
  CONSTRAINT `fk_unites_property_addresses1`
    FOREIGN KEY (`property_addresses_id`)
    REFERENCES `falcon`.`property_addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `taskName` VARCHAR(45) NULL,
  `issue_types_id` INT NOT NULL,
  `taskDescription` TEXT(1000) NULL,
  `property_addresses_id` INT NOT NULL,
  `unites_id` INT NOT NULL,
  `location` VARCHAR(45) NULL,
  `taskTime` VARCHAR(45) NULL,
  `taskDaysOfWeek_id` INT NOT NULL,
  `alertIfLeftOpen` INT NULL,
  `disableTaskAfterDate` DATE NULL,
  `lastIssuedDate` DATE NULL,
  `taskCurrentStatus` VARCHAR(45) NULL,
  `isActive` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tasks_issue_types1_idx` (`issue_types_id` ASC) VISIBLE,
  INDEX `fk_tasks_property_addresses1_idx` (`property_addresses_id` ASC) VISIBLE,
  INDEX `fk_tasks_taskDaysOfWeek1_idx` (`taskDaysOfWeek_id` ASC) VISIBLE,
  INDEX `fk_tasks_unites1_idx` (`unites_id` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_issue_types1`
    FOREIGN KEY (`issue_types_id`)
    REFERENCES `falcon`.`issue_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_property_addresses1`
    FOREIGN KEY (`property_addresses_id`)
    REFERENCES `falcon`.`property_addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_taskDaysOfWeek1`
    FOREIGN KEY (`taskDaysOfWeek_id`)
    REFERENCES `falcon`.`taskDaysOfWeek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_unites1`
    FOREIGN KEY (`unites_id`)
    REFERENCES `falcon`.`unites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`property_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`property_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `groupName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`group_has_properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`group_has_properties` (
  `property_id` INT NOT NULL,
  `property_group_id` INT NOT NULL,
  PRIMARY KEY (`property_id`, `property_group_id`),
  INDEX `fk_property_group_has_property_property1_idx` (`property_id` ASC) VISIBLE,
  INDEX `fk_property_group_has_property_property_group1_idx` (`property_group_id` ASC) VISIBLE,
  CONSTRAINT `fk_property_group_has_property_property_group1`
    FOREIGN KEY (`property_group_id`)
    REFERENCES `falcon`.`property_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_property_group_has_property_property1`
    FOREIGN KEY (`property_id`)
    REFERENCES `falcon`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`securityRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`securityRoles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roleName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`employee_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`employee_roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `webAccess` TINYINT NULL,
  `mobileLogin` TINYINT NULL,
  `lockProperty` TINYINT NULL,
  `addUsers` TINYINT NULL,
  `submitIssue` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`users_notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`users_notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `send meADailyMissedCheckpointReport` TINYINT NULL,
  `propertyIssuesPerHourFallBelowThreshold` TINYINT NULL,
  `overdueTasks` TINYINT NULL,
  `alertWhenUnableToSendTourStartMessages` TINYINT NULL,
  `alertWhenATourExpiresOrIsFinishedWithoutAllCheckpointsBeingHit` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `emailAddress` VARCHAR(45) NULL,
  `userName` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `active` TINYINT NULL,
  `securityRoles_id` INT NOT NULL,
  `maintananceEmail` VARCHAR(45) NULL,
  `timeCardID` VARCHAR(45) NULL,
  `cellNumber` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `states_id` INT NOT NULL,
  `zip` VARCHAR(45) NULL,
  `allowSecurityAssignments` TINYINT NULL,
  `allowParkingAssignments` TINYINT NULL,
  `allowMaintenanceAssignments` TINYINT NULL,
  `allowUserToviewGPSData` TINYINT NULL,
  `allowEmails` TINYINT NULL,
  `avatar` VARCHAR(255) NULL,
  `lastLoginDate` DATETIME NULL,
  `managmentCompany` INT NULL,
  `employee_roles_id` INT NULL,
  `users_notification_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_securityRoles1_idx` (`securityRoles_id` ASC) VISIBLE,
  INDEX `fk_users_states1_idx` (`states_id` ASC) VISIBLE,
  INDEX `fk_employees_clients_companies1_idx` (`managmentCompany` ASC) VISIBLE,
  INDEX `fk_employees_employee_roles1_idx` (`employee_roles_id` ASC) VISIBLE,
  INDEX `fk_employees_users_notification1_idx` (`users_notification_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_securityRoles1`
    FOREIGN KEY (`securityRoles_id`)
    REFERENCES `falcon`.`securityRoles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_states1`
    FOREIGN KEY (`states_id`)
    REFERENCES `falcon`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_clients_companies1`
    FOREIGN KEY (`managmentCompany`)
    REFERENCES `falcon`.`clients_companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_employee_roles1`
    FOREIGN KEY (`employee_roles_id`)
    REFERENCES `falcon`.`employee_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_users_notification1`
    FOREIGN KEY (`users_notification_id`)
    REFERENCES `falcon`.`users_notification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`notification` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `sendMeDailyMissedCheckpointReport` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notification_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_notification_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `falcon`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`devices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` TINYINT NULL,
  `registered` VARCHAR(45) NULL,
  `last Login` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `deviceID` VARCHAR(255) NULL,
  `carrierName` VARCHAR(45) NULL,
  `activationHistory` VARCHAR(45) NULL,
  `friendlyName` VARCHAR(45) NULL,
  `userZebraPrinter` TINYINT NULL,
  `requireGPS` TINYINT NULL,
  `userAutoFocus` TINYINT NULL,
  `barcodeScanner` TINYINT NULL,
  `active` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`general`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`general` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `localUrl` VARCHAR(45) NULL,
  `hideHomePageMenuBar` TINYINT NULL,
  `homePageMenuLinkName` VARCHAR(45) NULL,
  `returnURLonLogout` VARCHAR(45) NULL,
  `dispachPhoneNumber` VARCHAR(45) NULL,
  `dispachPhoenNumberGuards` VARCHAR(45) NULL,
  `timeZone` VARCHAR(45) NULL,
  `contactCompanyName` VARCHAR(45) NULL,
  `contactAddress` INT NULL,
  `city` VARCHAR(45) NULL,
  `states_id` INT NOT NULL,
  `contactEmail` VARCHAR(45) NULL,
  `contactPhoneNumber` VARCHAR(45) NULL,
  `handheldPhotoTimestampText` VARCHAR(45) NULL,
  `renderHomePageAsHTMLMarkup` TINYINT NULL,
  `IncludeArrivals/DeparturesInDAR` TINYINT NULL,
  `HomePageMessage` TEXT(1000) NULL,
  `MobileDeviceLoginMessage` VARCHAR(45) NULL,
  `hideDropDownCitySelector` TINYINT NULL,
  `propertyFindExampleText` TEXT(1000) NULL,
  `externalUrlLinks` TEXT(1000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`login_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`login_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `admin_id` INT NULL,
  `loginTimestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`issues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`issues` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `properties_id` INT NOT NULL,
  `issue_types_id` INT NOT NULL,
  `reportedDetail` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `reportedAddress` VARCHAR(45) NULL,
  `approxOccurrenceTime` VARCHAR(45) NULL,
  `property_addresses_id` INT NOT NULL,
  `status` TINYINT NULL,
  `created` TIMESTAMP NULL,
  `assigned` TIMESTAMP NULL,
  `ack` TIMESTAMP NULL,
  `arrived` TIMESTAMP NULL,
  `closed` TINYINT NULL,
  `createdBy` INT NOT NULL,
  `assignedTo` INT NOT NULL,
  `gpsLongitude` VARCHAR(45) NULL,
  `gpsLatitude` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_issues_properties1_idx` (`properties_id` ASC) VISIBLE,
  INDEX `fk_issues_issue_types1_idx` (`issue_types_id` ASC) VISIBLE,
  INDEX `fk_issues_property_addresses1_idx` (`property_addresses_id` ASC) VISIBLE,
  INDEX `fk_issues_users1_idx` (`createdBy` ASC) VISIBLE,
  INDEX `fk_issues_users2_idx` (`assignedTo` ASC) VISIBLE,
  CONSTRAINT `fk_issues_properties1`
    FOREIGN KEY (`properties_id`)
    REFERENCES `falcon`.`properties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issues_issue_types1`
    FOREIGN KEY (`issue_types_id`)
    REFERENCES `falcon`.`issue_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issues_property_addresses1`
    FOREIGN KEY (`property_addresses_id`)
    REFERENCES `falcon`.`property_addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issues_users1`
    FOREIGN KEY (`createdBy`)
    REFERENCES `falcon`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issues_users2`
    FOREIGN KEY (`assignedTo`)
    REFERENCES `falcon`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`issues_photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`issues_photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `issues_id` INT NOT NULL,
  `photoURL` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_issues_photos_issues1_idx` (`issues_id` ASC) VISIBLE,
  CONSTRAINT `fk_issues_photos_issues1`
    FOREIGN KEY (`issues_id`)
    REFERENCES `falcon`.`issues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`issues_sound`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`issues_sound` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `issues_id` INT NOT NULL,
  `soundURL` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_issues_sound_issues1_idx` (`issues_id` ASC) VISIBLE,
  CONSTRAINT `fk_issues_sound_issues1`
    FOREIGN KEY (`issues_id`)
    REFERENCES `falcon`.`issues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`systems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`systems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `general_id` INT NOT NULL,
  `devices_id` INT NOT NULL,
  `logos_id` INT NOT NULL,
  `notification_id` INT NOT NULL,
  `email_id` VARCHAR(45) NOT NULL,
  `domainName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_systems_general1_idx` (`general_id` ASC) VISIBLE,
  INDEX `fk_systems_devices1_idx` (`devices_id` ASC) VISIBLE,
  INDEX `fk_systems_logos1_idx` (`logos_id` ASC) VISIBLE,
  INDEX `fk_systems_notification1_idx` (`notification_id` ASC) VISIBLE,
  INDEX `fk_systems_email1_idx` (`email_id` ASC) VISIBLE,
  CONSTRAINT `fk_systems_general1`
    FOREIGN KEY (`general_id`)
    REFERENCES `falcon`.`general` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_systems_devices1`
    FOREIGN KEY (`devices_id`)
    REFERENCES `falcon`.`devices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_systems_logos1`
    FOREIGN KEY (`logos_id`)
    REFERENCES `falcon`.`logos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_systems_notification1`
    FOREIGN KEY (`notification_id`)
    REFERENCES `falcon`.`notification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_systems_email1`
    FOREIGN KEY (`email_id`)
    REFERENCES `falcon`.`email` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`property_group_has_employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`property_group_has_employees` (
  `property_group_id` INT NOT NULL,
  `employees_id` INT NOT NULL,
  PRIMARY KEY (`property_group_id`, `employees_id`),
  INDEX `fk_property_group_has_employees_employees1_idx` (`employees_id` ASC) VISIBLE,
  INDEX `fk_property_group_has_employees_property_group1_idx` (`property_group_id` ASC) VISIBLE,
  CONSTRAINT `fk_property_group_has_employees_property_group1`
    FOREIGN KEY (`property_group_id`)
    REFERENCES `falcon`.`property_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_property_group_has_employees_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `falcon`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`customer_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`customer_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `webAccess` TINYINT NULL,
  `mobileLogin` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `emailAddress` VARCHAR(45) NULL,
  `userName` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `active` TINYINT NULL,
  `securityRoles_id` INT NOT NULL,
  `maintananceEmail` VARCHAR(45) NULL,
  `timeCardID` VARCHAR(45) NULL,
  `cellNumber` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `states_id` INT NOT NULL,
  `zip` VARCHAR(45) NULL,
  `allowSecurityAssignments` TINYINT NULL,
  `allowParkingAssignments` TINYINT NULL,
  `allowMaintenanceAssignments` TINYINT NULL,
  `allowUserToviewGPSData` TINYINT NULL,
  `allowEmails` TINYINT NULL,
  `avatar` VARCHAR(255) NULL,
  `lastLoginDate` DATETIME NULL,
  `managmentCompany` INT NULL,
  `users_notification_id` INT NULL,
  `customer_roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_securityRoles1_idx` (`securityRoles_id` ASC) VISIBLE,
  INDEX `fk_users_states1_idx` (`states_id` ASC) VISIBLE,
  INDEX `fk_employees_clients_companies1_idx` (`managmentCompany` ASC) VISIBLE,
  INDEX `fk_employees_users_notification1_idx` (`users_notification_id` ASC) VISIBLE,
  INDEX `fk_customers_customer_roles1_idx` (`customer_roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_securityRoles10`
    FOREIGN KEY (`securityRoles_id`)
    REFERENCES `falcon`.`securityRoles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_states10`
    FOREIGN KEY (`states_id`)
    REFERENCES `falcon`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_clients_companies10`
    FOREIGN KEY (`managmentCompany`)
    REFERENCES `falcon`.`clients_companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_users_notification10`
    FOREIGN KEY (`users_notification_id`)
    REFERENCES `falcon`.`users_notification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_customer_roles1`
    FOREIGN KEY (`customer_roles_id`)
    REFERENCES `falcon`.`customer_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`clients_companies_has_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`clients_companies_has_customers` (
  `clients_companies_id` INT NOT NULL,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`clients_companies_id`, `customers_id`),
  INDEX `fk_clients_companies_has_customers_customers1_idx` (`customers_id` ASC) VISIBLE,
  INDEX `fk_clients_companies_has_customers_clients_companies1_idx` (`clients_companies_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_companies_has_customers_clients_companies1`
    FOREIGN KEY (`clients_companies_id`)
    REFERENCES `falcon`.`clients_companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_companies_has_customers_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `falcon`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`clients_companies_has_employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`clients_companies_has_employees` (
  `clients_companies_id` INT NOT NULL,
  `employees_id` INT NOT NULL,
  PRIMARY KEY (`clients_companies_id`, `employees_id`),
  INDEX `fk_clients_companies_has_employees_employees1_idx` (`employees_id` ASC) VISIBLE,
  INDEX `fk_clients_companies_has_employees_clients_companies1_idx` (`clients_companies_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_companies_has_employees_clients_companies1`
    FOREIGN KEY (`clients_companies_id`)
    REFERENCES `falcon`.`clients_companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_companies_has_employees_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `falcon`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`sent_email_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`sent_email_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `from` VARCHAR(45) NULL,
  `destination` VARCHAR(45) NULL,
  `body` VARCHAR(45) NULL,
  `emailSent` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`systems_has_employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`systems_has_employees` (
  `systems_id` INT NOT NULL,
  `employees_id` INT NOT NULL,
  PRIMARY KEY (`systems_id`, `employees_id`),
  INDEX `fk_systems_has_employees_employees1_idx` (`employees_id` ASC) VISIBLE,
  INDEX `fk_systems_has_employees_systems1_idx` (`systems_id` ASC) VISIBLE,
  CONSTRAINT `fk_systems_has_employees_systems1`
    FOREIGN KEY (`systems_id`)
    REFERENCES `falcon`.`systems` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_systems_has_employees_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `falcon`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`systems_has_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`systems_has_customers` (
  `systems_id` INT NOT NULL,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`systems_id`, `customers_id`),
  INDEX `fk_systems_has_customers_customers1_idx` (`customers_id` ASC) VISIBLE,
  INDEX `fk_systems_has_customers_systems1_idx` (`systems_id` ASC) VISIBLE,
  CONSTRAINT `fk_systems_has_customers_systems1`
    FOREIGN KEY (`systems_id`)
    REFERENCES `falcon`.`systems` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_systems_has_customers_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `falcon`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`systems_has_properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`systems_has_properties` (
  `systems_id` INT NOT NULL,
  `properties_id` INT NOT NULL,
  `properties_clients_companies_id` INT NOT NULL,
  PRIMARY KEY (`systems_id`, `properties_id`, `properties_clients_companies_id`),
  INDEX `fk_systems_has_properties_properties1_idx` (`properties_id` ASC, `properties_clients_companies_id` ASC) VISIBLE,
  INDEX `fk_systems_has_properties_systems1_idx` (`systems_id` ASC) VISIBLE,
  CONSTRAINT `fk_systems_has_properties_systems1`
    FOREIGN KEY (`systems_id`)
    REFERENCES `falcon`.`systems` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_systems_has_properties_properties1`
    FOREIGN KEY (`properties_id` , `properties_clients_companies_id`)
    REFERENCES `falcon`.`properties` (`id` , `clients_companies_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `falcon`.`systems_has_property_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `falcon`.`systems_has_property_group` (
  `systems_id` INT NOT NULL,
  `property_group_id` INT NOT NULL,
  PRIMARY KEY (`systems_id`, `property_group_id`),
  INDEX `fk_systems_has_property_group_property_group1_idx` (`property_group_id` ASC) VISIBLE,
  INDEX `fk_systems_has_property_group_systems1_idx` (`systems_id` ASC) VISIBLE,
  CONSTRAINT `fk_systems_has_property_group_systems1`
    FOREIGN KEY (`systems_id`)
    REFERENCES `falcon`.`systems` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_systems_has_property_group_property_group1`
    FOREIGN KEY (`property_group_id`)
    REFERENCES `falcon`.`property_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
